services: 
  wis2box-api:
    container_name: wis2box-api
    image: ghcr.io/wmo-im/wis2box-api:latest
    restart: always
    environment:
      - WIS2BOX_API_URL=${WIS2BOX_API_URL}
      - WIS2BOX_URL=${WIS2BOX_URL}
      - WIS2BOX_API_BACKEND_URL=$(WIS2BOX_API_BACKEND_URL)
      - WIS2BOX_BASEMAP_URL=${WIS2BOX_BASEMAP_URL}
      - WIS2BOX_BASEMAP_ATTRIBUTION=${WIS2BOX_BASEMAP_ATTRIBUTION}
      - WIS2BOX_BROKER_USERNAME=${WIS2BOX_BROKER_USERNAME}
      - WIS2BOX_BROKER_PASSWORD=${WIS2BOX_BROKER_PASSWORD}
      - WIS2BOX_BROKER_HOST=${WIS2BOX_BROKER_HOST}
      - WIS2BOX_BROKER_PORT=${WIS2BOX_BROKER_PORT}
      - WIS2BOX_STORAGE_SOURCE=${WIS2BOX_STORAGE_SOURCE}
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - api-config:/data/wis2box/config/pygeoapi/:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/oapi/admin/resources"]
      interval: 5s
      retries: 100

volumes:
  api-config: