services:
  wis2box-auth:
    container_name: wis2box-auth
    image: ghcr.io/wmo-im/wis2box-auth:latest
    restart: always
    env_file:
      - wis2box.env
    volumes:
      - ${AUTH_DATA}:/data/wis2box:rw
    depends_on:
      - wis2box-management