# define virtual network to give fixed IP for loki used by the logging-driver for all containers
networks:
  vpcbr: # virtual network name
    driver: bridge
    ipam:
     config: # here, we define our ip space
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1

# this is a YAML anchor to avoid repetition
x-logging: &logging
  logging:
    driver: loki
    options: # note: the ip is the ip we will assign later to loki in this file
      loki-url: "http://10.5.0.2:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"
      max-size: "10m"
      max-file: 1

services:
  # The Loki database for storing logs.
  loki:
    <<: *logging
    container_name: loki
    image: grafana/loki:2.4.1
    restart: always
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki-data:/loki
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml

  node_exporter:
    image: prom/node-exporter
    restart: always

  # mqtt_metrics_collector, listens to mqtt-broker
  mqtt_metrics_collector:
    <<: *logging
    container_name: mqtt_metrics_collector
    restart: unless-stopped
    env_file:
      - wis2box.env
    #image: ghcr.io/wmo-im/wis2box-mqtt-metrics-collector:1.0.beta1
    build:
      context: ./wis2box-mqtt-metrics-collector
    depends_on:
      - mosquitto
      - wis2box-management
    ports:
      - 8001:8001
    
  # prometheus to collect metrics
  prometheus:
    <<: *logging
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=10d'
    ports:
      - "9090:9090"

  # uncomment cadvisor to monitor containers
  # cadvisor:
  #  image: gcr.io/cadvisor/cadvisor:v0.45.0
  #  container_name: cadvisor
  #  volumes:
  #    - /:/rootfs:ro
  #    - /var/run:/var/run:ro
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - /sys:/sys:ro
  #    - /var/lib/docker/:/var/lib/docker:ro
  #    - /dev/disk:/dev/disk/:ro
  #  depends_on:
  #    - wis2box-management
  # Grafana, graphical monitoring dashboards for wis2box using data from loki and prometheus
  grafana:
    <<: *logging
    image: grafana/grafana-oss:9.0.3
    container_name: grafana
    restart: always
    env_file:
      - wis2box.env
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=true
      - GF_USERS_DEFAULT_THEME=dark
      - GF_DISABLE_SIGNOUT_MENU=true
      - GF_SERVER_ROOT_URL=${WIS2BOX_URL:-http://localhost}/monitoring
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    ports:
      - 3000:3000

  # Elasticsearch Exporter for monitoring Elasticsearch metrics
  elasticsearch-exporter:
    <<: *logging
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
      - '--es.uri=http://elasticsearch:9200'
      - '--es.indices_settings'
    restart: always

  wis2box-management:
    <<: *logging
  mosquitto:
    <<: *logging
  wis2box-api:
    <<: *logging
  elasticsearch:
    <<: *logging
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    ports:
      - "9200:9200"

  wis2box-auth:
    <<: *logging
  minio:
    <<: *logging
  web-proxy:
    <<: *logging
  wis2downloader:
    <<: *logging

volumes:
  loki-data:
  prometheus-data:

