services:
  wis2box-management:
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
      - ./wis2box-management/wis2box/wis2box.cron:/etc/cron.d/wis2box:ro
      - ./wis2box-management/wis2box:/app/wis2box
    command: ["wis2box", "pubsub" , "subscribe", "--broker", "http://wis2box-minio:9000", "--topic", "wis2box-storage/#", "--verbosity", "INFO"]

  wis2box-api:
    volumes:
      - ../wis2box-api/wis2box_api:/app/wis2box_api

  elasticsearch:
    ports:
      - 9200:9200
