services:
  web-proxy:
    ports:
      - 80:80

  wis2box-ui:
    ports:
      - 9999:80

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      replicas: 1

  mosquitto:
    ports:
      - 1883:1883
      - 8884:8884

  postgres:
    ports:
      - 5432:5432

  keycloak:
    ports:
      - 8180:8180
      - 4180:4180
