services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - wis2box.env
    depends_on:
      - wis2box-ui
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - htpasswd:/etc/nginx/.htpasswd:ro

  wis2box-ui:
    container_name: wis2box-ui
    image: ghcr.io/wmo-im/wis2box-ui:latest
    restart: always
    env_file:
      - wis2box.env
    depends_on:
      - wis2box-api

  wis2box-webapp:
    container_name: wis2box-webapp
    image: ghcr.io/wmo-im/wis2box-webapp:latest
    env_file:
      - wis2box.env
    restart: always

  wis2box-api:
    container_name: wis2box-api
    image: ghcr.io/wmo-im/wis2box-api:latest
    restart: always
    env_file:
      - wis2box.env
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/oapi/admin/resources"]
      interval: 5s
      retries: 100
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/mappings:/data/wis2box/mappings:ro

  minio:
    container_name: wis2box-minio
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z-cpuv1
    mem_limit: 512m
    memswap_limit: 512m
    restart: always
    env_file:
      - wis2box.env
    environment:
      - MINIO_BROWSER_LOGIN_ANIMATION=off
      - MINIO_BROWSER_REDIRECT=false
      - MINIO_UPDATE=off
    command: server --quiet --console-address ":9001" --sftp="address=:8022" --sftp="ssh-private-key=/home/miniouser/.ssh/id_rsa" /data
    volumes:
      - minio-data:/data
      - ${WIS2BOX_HOST_DATADIR}/.ssh:/home/miniouser/.ssh:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      mosquitto:
        condition: service_started

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=[]
      - node.name=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=es-wis2box
      - xpack.security.enabled=false
      - ingest.geoip.downloader.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - xpack.monitoring.templates.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    mem_limit: 1.5g
    memswap_limit: 1.5g
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      retries: 100

  mosquitto:
    container_name: mosquitto
    image: ghcr.io/wmo-im/wis2box-broker:latest
    restart: always
    env_file:
      - wis2box.env
    volumes:
      - mosquitto-config:/mosquitto/config

  wis2box-management:
    container_name: wis2box-management
    image: ghcr.io/wmo-im/wis2box-management:latest
    mem_limit: 1g
    memswap_limit: 1g
    restart: always
    env_file:
      - wis2box.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
      - htpasswd:/home/wis2box/.htpasswd:rw
    depends_on:
      mosquitto:
        condition: service_started
      wis2box-api:
        condition: service_healthy
    command: ["wis2box", "pubsub" , "subscribe"]

  # mqtt_metrics_collector, listens to mqtt-broker
  mqtt_metrics_collector:
    container_name: mqtt_metrics_collector
    restart: unless-stopped
    env_file:
      - wis2box.env
    image: ghcr.io/wmo-im/wis2box-mqtt-metrics-collector:latest
    depends_on:
      - mosquitto
      - wis2box-management
    ports:
      - 8001:8001

  wis2box-auth:
    container_name: wis2box-auth
    image: ghcr.io/wmo-im/wis2box-auth:latest
    restart: always
    env_file:
      - wis2box.env
    volumes:
      - auth-data:/data/wis2box:rw
    depends_on:
      - wis2box-management

  wis2downloader:
    container_name: wis2downloader
    image: ghcr.io/wmo-im/wis2downloader:v0.3.2
    restart: always
    env_file:
      - wis2box.env
    user: 12135:${DOCKER_GID}
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/downloads:/home/wis2downloader/app/data/downloads

volumes:
  es-data:
  minio-data:
  auth-data:
  htpasswd:
  mosquitto-config:
