services:
  wis2box-management:
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
      - ./wis2box-management/wis2box/wis2box.cron:/etc/cron.d/wis2box:ro
      - ./wis2box-management/wis2box:/app/wis2box
    command: ["wis2box", "pubsub" , "subscribe"]

  wis2box-api:
    volumes:
      - ../wis2box-api/wis2box_api:/app/wis2box_api

  wis2box-auth:
    volumes:
      - ../wis2box-auth/wis2box_auth:/app/wis2box_auth

  elasticsearch:
    ports:
      - 9200:9200
