services:
  wis2box-api:
    container_name: wis2box-subscribe-download
    build:
      context: wis2box-subscribe-download 
    volumes:
      - subscribe-download:/data/wis2box-subscribe-download

volumes:
  subscribe-download:
