services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - wis2box.env
    depends_on:
      - wis2box-ui
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - monitoring

  wis2box-ui:
    container_name: wis2box-ui
    image: ghcr.io/wmo-im/wis2box-ui:latest
    restart: always
    env_file:
      - wis2box.env
    depends_on:
      - wis2box-api
    networks:
      - monitoring

#  wis2box-ui-admin:
#    container_name: wis2box-ui-admin
#    image: ghcr.io/wmo-im/wis2box-ui-admin:latest
#    restart: always
#    env_file:
#      - wis2box.env
#    depends_on:
#      - wis2box-api

  wis2box-webapp:
    container_name: wis2box-webapp
    image: ghcr.io/wmo-im/wis2box-webapp:latest
    restart: always
    env_file:
      - wis2box.env
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.0.3
    ports:
      - "3000:3000"
    restart: always
    networks:
      - monitoring

  loki:
    container_name: loki
    image: grafana/loki:2.4.1
    restart: always
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  node_exporter:
    image: prom/node-exporter
    networks:
      - monitoring

  mqtt_metrics_collector:
    container_name: mqtt_metrics_collector
    image: wis2box_project-mqtt_metrics_collector
    restart: always  
    networks:
      - monitoring

  wis2box-api:
    container_name: wis2box-api
    image: ghcr.io/wmo-im/wis2box-api:latest
    restart: always
    env_file:
      - wis2box.env
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - api-config:/data/wis2box/config/pygeoapi/:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/oapi/admin/resources"]
      interval: 5s
      retries: 100
    networks:
      - monitoring

  minio:
    container_name: wis2box-minio
    image: minio/minio
    mem_limit: 512m
    memswap_limit: 512m
    restart: always
    env_file:
      - wis2box.env
    environment:
      - MINIO_BROWSER_LOGIN_ANIMATION=off
    command: server --console-address ":9001" /data
    # in a production-setup minio needs to be
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      mosquitto:
        condition: service_started
    networks:
      - monitoring

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=[]
      - node.name=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=es-wis2box
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    mem_limit: 1.5g
    memswap_limit: 1.5g
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      retries: 100
    networks:
      - monitoring

  mosquitto:
    container_name: mosquitto
    #image: ghcr.io/wmo-im/wis2box-broker:1.0.beta1
    restart: always
    build:
      context: ./wis2box-broker
    env_file:
      - wis2box.env
    networks:
      - monitoring

  wis2box-management:
    container_name: wis2box-management
    mem_limit: 1g
    memswap_limit: 1g
    restart: always
    #image: ghcr.io/wmo-im/wis2box-management:1.0.beta1
    build:
      context: ./wis2box-management
    #user: wis2box:wis2box
    env_file:
      - wis2box.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
      - htpasswd:/home/wis2box/.htpasswd:rw
    depends_on:
      minio:
        condition: service_healthy
      mosquitto:
        condition: service_started
      wis2box-api:
        condition: service_healthy
    command: ["wis2box", "pubsub" , "subscribe"]
    networks:
      - monitoring

  wis2box-auth:
    container_name: wis2box-auth
    image: ghcr.io/wmo-im/wis2box-auth:latest
    restart: always
    env_file:
      - wis2box.env
    volumes:
      - auth-data:/data/wis2box:rw
    depends_on:
      - wis2box-management
    networks:
      - monitoring

  wis2downloader:
    container_name: wis2downloader
    image: wis2box_project-wis2downloader
    restart: always
    build: ./wis2downloader
    env_file:
      - wis2box.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/downloads:/app/downloads:rw
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  es-data:
    driver: local
  minio-data:
  auth-data:
  api-config:
  htpasswd: