wis2box:
    retention: P30D
    topic_hierarchy: centre_id.data.core.weather.surface-based-observations.synop
    country: country
    centre_id: centre_id

mcf:
    version: 1.0

metadata:
    identifier: urn:wmo:md:centre_id:surface-weather-observations
    language: en
    charset: utf8
    hierarchylevel: dataset

identification:
    language: en
    charset: utf8
    title: Surface weather observations from centre_id
    abstract: Surface weather observations from centre_id
    dates:
        creation: 2021-11-29
        publication: 2021-11-29
    keywords:
        default:
            keywords:
                - surface weather
                - temperature
                - observations
        wmo:
            keywords:
                - weather
            keywords_type: theme
            vocabulary:
                name: WMO WIS2 Topic Hierarchy
                url: https://codes.wmo.int/topic-hierarchy/earth-system-discipline
    extents:
        spatial:
            - bbox: [-180, -90, 190, 90]
              crs: 4326
        temporal:
            - begin: 2021-11-29
              end: null
              resolution: P1H
    url: https://example.org/surface-weather-observations-webpage
    wmo_data_policy: core

contact:
    host:
        organization: Your organization name
        url: https://example.org
        individualname: Firstname Lastname
        positionname: Position Name
        phone: null
        fax: null
        address: null
        city: null
        administrativearea: null
        postalcode: null
        country: null
        email: you@example.org
        hoursofservice: 0700h - 1500h UTC
        contactinstructions: email
