wis2box:
    retention: P30D
    topic_hierarchy: iso3c_country.centre_id.data.core.weather.surface-based-observations.synop
    country: iso3c_country
    centre_id: centre_id

mcf:
    version: 1.0

metadata:
    identifier: iso3c_country.centre_id.data.core.weather.surface-based-observations.synop
    language: en
    language_alternate: fr
    charset: utf8
    hierarchylevel: dataset
    datestamp: 2021-11-29

spatial:
    datatype: vector
    geomtype: point

identification:
    language: en
    charset: utf8
    title:
        en: Surface weather observations from iso3c_country.centre_id
    abstract:
        en: Surface weather observations from iso3c_country.centre_id
    dates:
        creation: 2021-11-29
        publication: 2021-11-29
    keywords:
        default:
            keywords:
                en:
                    - surface weather
                    - temperature
                    - observations
        wmo:
            keywords:
                en:
                    - weatherObservations
            keywords_type: theme
            vocabulary:
                name:
                    en: WMO Category Code
                url: https://github.com/wmo-im/wcmp-codelists/blob/main/codelists/WMO_CategoryCode.csv

    topiccategory:
        - climatologyMeteorologyAtmosphere
    extents:
        spatial:
            - bbox: [0., 360., -90., 90.]
              crs: 4326
        temporal:
            - begin: 2021-11-29
              end: null
              resolution: P1H
    fees: None
    accessconstraints: otherRestrictions
    rights:
        en: WMO Unified Policy for the International Exchange of Earth System Data
    url: your.url
    status: onGoing
    maintenancefrequency: continual

contact:
    pointOfContact: &contact_poc
        organization: WMO
        url: http://contact.url
        individualname: Firstname Lastname
        positionname: Position Name
        phone: NA
        fax: NA
        address: NA
        city: NA
        administrativearea: NA
        postalcode: NA
        country: NA
        email: you@example.org
        hoursofservice: 0700h - 1500h UTC
        contactinstructions: email

    distributor: *contact_poc

dataquality:
    scope:
        level: dataset
    lineage:
        statement: this data was generated by the bufr2geojson tool
