data:
    [country].[centre_id].data.core.weather.surface-based-observations.synop:
        plugins:
            txt:
                - plugin: wis2box.data.synop2bufr.ObservationDataSYNOP2BUFR
                  notify: true
                  file-pattern: '^A_SMR.*EDZW_(\d{4})(\d{2}).*.txt$'
            bufr4:
                - plugin: wis2box.data.bufr2geojson.ObservationDataBUFR2GeoJSON
                  file-pattern: '^A_SMR.*EDZW_(\d{4})(\d{2}).*.bufr4$'
