broker: mqtts://host:port

verify_data: true

#validate_message: true

subscribe_topics:
    - '#'

# storage: filesystem
storage:
    type: fs
    options:
        path: /data/wis2box-subscribe-download
