version: "3"

services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - ../dev.env
      - docker.env
    depends_on:
      - wis2node-ui
    volumes:
      - ${WIS2NODE_DATADIR}/data:/data/wis2node/data:ro,z
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2node-ui:
    container_name: wis2node-ui
    image: ghcr.io/wmo-im/wis2node-ui:latest
    depends_on:
      - pygeoapi

  pygeoapi:
    container_name: pygeoapi
    #image: geopython/pygeoapi:latest
    build:
      context: ./pygeoapi
    env_file:
      - ../dev.env
      - docker.env
    environment:
      - SCRIPT_NAME=/pygeoapi
    depends_on:
      - elasticsearch
    volumes:
      - ${WIS2NODE_DATADIR}/data:/data/wis2node/data:ro,z
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - xpack.security.enabled=true  # TODO: setup credentials
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 5s
      retries: 10

  mosquitto:
    container_name: mosquitto
    # image: eclipse-mosquitto
    build:
      context: ./mosquitto
    env_file:
      - ../dev.env
      - docker.env
    volumes:
      - ${WIS2NODE_DATADIR}/data:/data/wis2node/data:rw,z

  data-consumer:
    container_name: data-consumer
    # image: ghcr.io/metpx/sarracenia:latest
    build:
      context: ./data-consumer
    #user: sarra:sarra
    env_file:
      - ../dev.env
      - docker.env
    volumes:
      - ${WIS2NODE_DATADIR}/data:/data/wis2node/data:rw,z
    depends_on:
      - mosquitto

  wis2node:
    container_name: wis2node
    build: 
      context: ..
      args:
        WIS2NODE_PIP3_EXTRA_PACKAGES: ${WIS2NODE_PIP3_EXTRA_PACKAGES}
    #user: wis2node:wis2node
    env_file:
      - ../dev.env
      - docker.env
    volumes:
      - ${WIS2NODE_DATADIR}/data:/data/wis2node/data:rw,z
      - ./wis2node/config:/root/.config/sr3:ro
      - ./wis2node/wis2node.cron:/etc/cron.d/wis2node:ro
      - ./pygeoapi/pygeoapi-config.yml:/data/wis2node/pygeoapi-config.yml:rw,z
    depends_on:
      - mosquitto
volumes:
  es-data:
