services:
  web-proxy:
    ports:
      - 8999:80

  wis2box-ui:
    ports:
      - 9999:80

  wis2box-auth:
    ports:
      - 12345:80

  wis2box-api:
    ports:
      - 5001:80

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      replicas: 1

  elasticsearch:
    ports:
      - 9200:9200

  mosquitto:
    ports:
      - 1883:1883
