services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-ui
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data/public:/data/wis2box/data/public:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2box-ui:
    container_name: wis2box-ui
    image: ghcr.io/wmo-im/wis2box-ui:latest
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-api

  wis2box-api:
    container_name: wis2box-api
    image: ghcr.io/wmo-im/wis2box-api:latest
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      elasticsearch:
        condition: service_healthy
      wis2box:
        condition: service_started
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:ro

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - xpack.security.enabled=true  # TODO: setup credentials
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 5s
      retries: 100

  mosquitto:
    container_name: mosquitto
    # image: eclipse-mosquitto
    build:
      context: ./mosquitto
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw

  data-consumer:
    container_name: data-consumer
    build:
      context: ..
    #user: wis2box:wis2box
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
    depends_on:
      - mosquitto
    command: sh -c "wis2box pubsub watch --path /data/wis2box/data/incoming --verbosity INFO"

  mqp-publisher:
    container_name: mqp-publisher
    image: ghcr.io/metpx/sarracenia:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
      - ./sarracenia/admin.conf:/root/.config/sr3/admin.conf:rw
      - ./sarracenia/default.conf:/root/.config/sr3/default.conf:rw
      - ./sarracenia/public.conf:/root/.config/sr3/subscribe/public.conf:rw
    depends_on:
      - mosquitto
    command: sh -c "whoami && sr3 --logStdout start && sleep infinity"

  wis2box:
    container_name: wis2box
    build:
      context: ..
      # args:
      #   WIS2BOX_PIP3_EXTRA_PACKAGES: ${WIS2BOX_PIP3_EXTRA_PACKAGES}
    #user: wis2box:wis2box
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
      - ./wis2box/wis2box.cron:/etc/cron.d/wis2box:ro
    depends_on:
      - mosquitto
    command: sh -c "sr3 --logStdout start && sleep infinity"

  wis2box-auth:
    container_name: wis2box-auth
    build:
      context: ./auth
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
    depends_on:
      - wis2box
volumes:
  es-data:


