version: "2.2"

services:
  web-proxy:
    ports:
      - 8999:80

  wis2node-ui:
    ports:
      - 9999:80

  pygeoapi:
    ports:
      - 5000:80

  elasticsearch:
    ports:
      - 9200:9200

  mosquitto:
    ports:
      - 1883:1883
