version: "3"

# define virtual network to give fixed IP for loki
networks:
  vpcbr: # virtual network name
    driver: bridge
    ipam:
     config: # here, we define our ip space
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1

# this is a YAML anchor to avoid repetition
x-logging: &logging
  logging:
    driver: loki
    options: # note: the ip is the ip we will assign later to loki in this file
      loki-url: "http://10.5.0.2:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"

services:
  # The Loki database for storing logs.
  loki:
    container_name: loki
    image: grafana/loki:2.4.1
    volumes:
      - loki-data:/loki
    networks:
      vpcbr: # this is the place where we assign the static ipv4 address
        ipv4_address: 10.5.0.2
      default:
  # cadvisor to export metrics on our containers
  cadvisor:
    <<: *logging
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
  # prometheus to collect metrics
  prometheus:
    <<: *logging
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  # Grafana, graphical monitoring dashboards for wis2box using data from loki and prometheus
  grafana:
    <<: *logging
    container_name: grafana
    image: grafana/grafana-oss:latest
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=false
    ports:
      - 3000:3000
  
  web-proxy:
    <<: *logging
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-ui
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data/public:/data/wis2box/data/public:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2box-ui:
    <<: *logging
    container_name: wis2box-ui
    image: ghcr.io/wmo-im/wis2box-ui:latest
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-api

  wis2box-api:
    container_name: wis2box-api
    image: ghcr.io/wmo-im/wis2box-api:latest
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - elasticsearch
      - wis2box
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:ro

  elasticsearch:
    <<: *logging
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - xpack.security.enabled=true  # TODO: setup credentials
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 5s
      retries: 10

  mosquitto:
    <<: *logging
    container_name: mosquitto
    # image: eclipse-mosquitto
    build:
      context: ./mosquitto
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
    depends_on:
      - loki

  data-consumer:
    <<: *logging
    container_name: data-consumer
    image: ghcr.io/metpx/sarracenia:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
      - ./sarracenia/admin.conf:/root/.config/sr3/admin.conf:rw
      - ./sarracenia/default.conf:/root/.config/sr3/default.conf:rw
      - ./sarracenia/incoming.conf:/root/.config/sr3/watch/incoming.conf:rw
    depends_on:
      - mosquitto
    command: sh -c "whoami && sr3 --logStdout start && sleep infinity"

  mqp-publisher:
    <<: *logging
    container_name: mqp-publisher
    image: ghcr.io/metpx/sarracenia:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
      - ./sarracenia/admin.conf:/root/.config/sr3/admin.conf:rw
      - ./sarracenia/default.conf:/root/.config/sr3/default.conf:rw
      - ./sarracenia/public.conf:/root/.config/sr3/subscribe/public.conf:rw
    depends_on:
      - mosquitto
    command: sh -c "whoami && sr3 --logStdout start && sleep infinity"

  ca-republisher:
    <<: *logging
    container_name: ca-republisher
    image: ghcr.io/metpx/sarracenia:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
      - ./sarracenia/admin.conf:/root/.config/sr3/admin.conf:rw
      - ./sarracenia/default.conf:/root/.config/sr3/default.conf:rw
      - ./sarracenia/subscribe/ca-republisher.conf:/root/.config/sr3/subscribe/ca-republisher.conf:rw
    depends_on:
      - mosquitto
    #command: sh -c "whoami && sr3 --logStdout start && sleep infinity"

  de-republisher:
    <<: *logging
    container_name: de-republisher
    image: ghcr.io/metpx/sarracenia:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
      - ./sarracenia/admin.conf:/root/.config/sr3/admin.conf:rw
      - ./sarracenia/default.conf:/root/.config/sr3/default.conf:rw
      - ./sarracenia/subscribe/de-republisher.conf:/root/.config/sr3/subscribe/de-republisher.conf:rw
    depends_on:
      - mosquitto
    # command: sh -c "whoami && sr3 --logStdout start && sleep infinity"

  wis2box:
    <<: *logging
    container_name: wis2box
    build:
      context: ..
      # args:
      #   WIS2BOX_PIP3_EXTRA_PACKAGES: ${WIS2BOX_PIP3_EXTRA_PACKAGES}
    #user: wis2box:wis2box
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
      - ./wis2box/wis2box.cron:/etc/cron.d/wis2box:ro
    depends_on:
      - mosquitto

  wis2box-auth:
    container_name: wis2box-auth
    build:
      context: ./auth
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
    depends_on:
      - wis2box

volumes:
  es-data:
  loki-data:
  prometheus-data:


