version: "3"

services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - pygeoapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2node-ui:
    container_name: wis2node-ui
    build: https://github.com/wmo-im/wis2node-ui.git#main

  pygeoapi:
    container_name: pygeoapi
    image: geopython/pygeoapi:latest
    environment:
      - SCRIPT_NAME=/pygeoapi
      - PYGEOAPI_SERVER_URL=http://localhost/pygeoapi
      - WIS2NODE_DATADIR=/data/wis2node
    volumes:
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro

  geohealthcheck-web:
    container_name: geohealthcheck_web
    image: geopython/geohealthcheck:latest
    restart: unless-stopped
    environment:
      - SCRIPT_NAME=/monitor
    env_file:
      - geohealthcheck/geohealthcheck.env
    volumes:
      - geohealthcheck_sqlitedb:/GeoHealthCheck/DB

  geohealthcheck-runner:
    container_name: geohealthcheck_runner
    image: geopython/geohealthcheck:latest
    restart: unless-stopped
    env_file:
      - geohealthcheck/geohealthcheck.env
    entrypoint:
      - /run-runner.sh
    volumes:
      - geohealthcheck_sqlitedb:/GeoHealthCheck/DB

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=wis2node
      - RABBITMQ_DEFAULT_PASS=wis2node

  metpx-sr3:
    container_name: metpx
    build: https://github.com/MetPX/sarracenia.git#v03_wip
    environment:
      - METPX_SR3_HOST=rabbitmq
      - METPX_SR3_BROKER_USERNAME=wis2node
      - METPX_SR3_BROKER_PASSWORD=wis2node
      - METPX_SR3_PATH_PUBLIC=/data/wis2node/data/public
      - METPX_SR3_BASEURL=http://wis2node-ui
      - METPX_SR3_LOGLEVEL=DEBUG
    volumes:
      - ./metpx-sr3/config:/home/sarra/.config/sr3:ro
      - ../wis2node-data/cache:/home/sarra/.cache:rw
      - ../wis2node-data:/data/wis2node:rw
    depends_on:
      - rabbitmq
    command: sh -c "sr3 start && sleep infinity"

volumes:
  geohealthcheck_sqlitedb:
