version: "3"

services:
  web-proxy:
    ports:
      - 8999:80

  wis2node-ui:
    ports:
      - 9999:80

  pygeoapi:
    ports:
      - 5000:80
    environment:
      - SCRIPT_NAME=/pygeoapi
      - PYGEOAPI_SERVER_URL=http://localhost:8999/pygeoapi
    volumes:
      - ../wis2node-data:/data/wis2node:rw

  geohealthcheck-web:
    ports:
      - 8083:80

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
