version: "3"

services:
  web-proxy:
    ports:
      - 8999:80

  wis2node-ui:
    ports:
      - 9999:80

  pygeoapi:
    ports:
      - 5000:80
    environment:
      - SCRIPT_NAME=/pygeoapi
      - PYGEOAPI_SERVER_URL=http://localhost:8999/pygeoapi
    volumes:
      - ${WIS2NODE_DATADIR}:/data/wis2node:rw

  mosquitto:
    ports:
      - 1883:1883
