version: "3"

services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    environment:
      - METPX_SR3_PATH_PUBLIC=/data/wis2node/data/public
    depends_on:
      - pygeoapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../wis2node-data/data/public:/data/wis2node/data/public:ro

  wis2node-ui:
    container_name: wis2node-ui
    build: https://github.com/wmo-im/wis2node-ui.git#main

  pygeoapi:
    container_name: pygeoapi
    image: geopython/pygeoapi:latest
    environment:
      - SCRIPT_NAME=/pygeoapi
      - PYGEOAPI_SERVER_URL=http://localhost/pygeoapi
      - WIS2NODE_DATADIR=/data/wis2node
    volumes:
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ../wis2node-data/mosquitto:/mosquitto/:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/entrypoint.sh:/entrypoint.sh
    entrypoint: /bin/sh /entrypoint.sh

  data-consumer:
    container_name: data-consumer
    build: https://github.com/MetPX/sarracenia.git#v03_wip
    environment:
      - METPX_SR3_HOST=mosquitto
      - METPX_SR3_BROKER_USERNAME=wis2node
      - METPX_SR3_BROKER_PASSWORD=wis2node
      - METPX_SR3_EXCHANGE=xs_wis2node_acquisition
      - METPX_SR3_PATH_INCOMING=/data/wis2node/data/incoming
      - METPX_SR3_PATH_PUBLIC=/data/wis2node/data/public
      - METPX_SR3_BASEURL=http://localhost
      - METPX_SR3_LOGLEVEL=DEBUG
    volumes:
      - ./data-consumer/config:/home/sarra/.config/sr3:ro
      - ../wis2node-data/cache/sarra:/home/sarra/.cache:rw
      - ../wis2node-data:/data/wis2node:rw
    depends_on:
      - mosquitto
    command: sh -c "sr3 start && sleep infinity"

  wis2node:
    container_name: wis2node
    build: ..
    environment:
      - METPX_SR3_HOST=mosquitto
      - METPX_SR3_BROKER_USERNAME=wis2node
      - METPX_SR3_BROKER_PASSWORD=wis2node
      - METPX_SR3_EXCHANGE=xs_wis2node_acquisition
      - METPX_SR3_PATH_INCOMING=/data/wis2node/data/incoming
      - METPX_SR3_PATH_PUBLIC=/data/wis2node/data/public
      - METPX_SR3_BASEURL=http://localhost
      - METPX_SR3_LOGLEVEL=DEBUG
      - WIS2NODE_DATADIR=/data/wis2node/data
      - WIS2NODE_DATADIR_INCOMING=/data/wis2node/data/incoming
      - WIS2NODE_DATADIR_OUTGOING=/data/wis2node/data/outgoing
      - WIS2NODE_DATADIR_PUBLIC=/data/wis2node/data/public
      - WIS2NODE_CATALOGUE_BACKEND=/data/wis2node/metadata/discovery/records.tinydb
      - WIS2NODE_OSCAR_API_TOKEN=some_token
      - WIS2NODE_URL=http://wis2node-ui/
      - WIS2NODE_OGC_API_URL=http://pygeoapi/pygeoapi
    volumes:
      - ./wis2node/config:/home/wis2node/.config/sr3:ro
      - ../wis2node-data/cache/wis2node:/home/wis2node/.cache:rw
      - ../wis2node-data:/data/wis2node:rw
    depends_on:
      - mosquitto
    command: sh -c "sr3 start && sleep infinity"
