version: "3"

services:
  web-proxy:
    ports:
      - 8999:80

  app:
    environment:
        - WIS2NODE_BASEURL=http://localhost:8999
    ports:
      - 9999:8000

  pygeoapi:
    ports:
      - 5000:80
    environment:
      - SCRIPT_NAME=/pygeoapi
      - PYGEOAPI_SERVER_URL=http://localhost:8999/pygeoapi

  geohealthcheck-web:
    ports:
      - 8083:80

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
