version: "3"

services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-ui
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data/public:/data/wis2node/data/public:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2box-ui:
    container_name: wis2box-ui
    image: ghcr.io/wmo-im/wis2box-ui:latest
    depends_on:
      - pygeoapi

  pygeoapi:
    container_name: pygeoapi
    #image: geopython/pygeoapi:latest
    build:
      context: ./pygeoapi
    env_file:
      - default.env
      - ../dev.env
    environment:
      - SCRIPT_NAME=/pygeoapi
    depends_on:
      - elasticsearch
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:ro
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch-01
      - discovery.seed_hosts=elasticsearch-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # - xpack.security.enabled=true  # TODO: setup credentials
    volumes:
      - es-data:/usr/share/elasticsearch/data:rw
    # ulimits:
    #   nofile:
    #     soft: 524288
    #     hard: 524288
    #   memlock:
    #     soft: -1
    #     hard: -1
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200"]
      interval: 5s
      retries: 10

  mosquitto:
    container_name: mosquitto
    # image: eclipse-mosquitto
    build:
      context: ./mosquitto
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw

  data-consumer:
    container_name: data-consumer
    image: ghcr.io/metpx/sarracenia_x64:latest
    build:
      context: ./data-consumer
    #user: sarra:sarra
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data:/data/wis2box/data:rw
    depends_on:
      - mosquitto

  wis2box:
    container_name: wis2box
    build:
      context: ..
      # args:
      #   WIS2BOX_PIP3_EXTRA_PACKAGES: ${WIS2BOX_PIP3_EXTRA_PACKAGES}
    #user: wis2box:wis2box
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/:/data/wis2box/:rw
      - ./wis2box/config:/root/.config/sr3:ro
      - ./wis2box/wis2box.cron:/etc/cron.d/wis2box:ro
      - ./pygeoapi/pygeoapi-config.yml:/data/wis2box/pygeoapi-config.yml:rw
    depends_on:
      - mosquitto
volumes:
  es-data:
