version: "3"

services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    depends_on:
      - pygeoapi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

  wis2node_app:
    container_name: wis2node_app
    build: ..
    ports:
      - 9999:8000

  pygeoapi:
    container_name: pygeoapi
    image: geopython/pygeoapi:latest
    ports:
      - 5000:80
    environment:
      - SCRIPT_NAME=/pygeoapi
      - PYGEOAPI_SERVER_URL=http://localhost/pygeoapi
    volumes:
      - ./pygeoapi/pygeoapi-config.yml:/pygeoapi/local.config.yml:ro

  geohealthcheck-web:
    container_name: geohealthcheck_web
    image: geopython/geohealthcheck:latest
    restart: unless-stopped
    environment:
      - SCRIPT_NAME=/monitor
    env_file:
      - geohealthcheck/geohealthcheck.env
    volumes:
      - geohealthcheck_sqlitedb:/GeoHealthCheck/DB
    ports:
      - 8083:80

  geohealthcheck-runner:
    container_name: geohealthcheck_runner
    image: geopython/geohealthcheck:latest
    restart: unless-stopped
    env_file:
      - geohealthcheck/geohealthcheck.env
    entrypoint:
      - /run-runner.sh
    volumes:
      - geohealthcheck_sqlitedb:/GeoHealthCheck/DB

volumes:
  geohealthcheck_sqlitedb:
