version: "3"

services:
  web-proxy:
    ports:
      - 8999:80

  wis2box-ui:
    ports:
      - 9999:80

  pygeoapi:
    ports:
      - 5001:80

  elasticsearch:
    ports:
      - 9200:9200

  mosquitto:
    ports:
      - 1883:1883
