services:
  wis2box-management:
    mem_limit: 1g
    memswap_limit: 1g
    restart: always
    build:
      context: ../wis2box-management
    environment:
      - WIS2BOX_URL=http://www.mywis2data.com
      - WIS2BOX_DOCKER_API_URL=http://wis2box-api:80/oapi
      - WIS2BOX_API_BACKEND_URL=http://elasticsearch:9200
      - MINIO_NOTIFY_MQTT_USERNAME_WIS2BOX=localbroker-admin
      - MINIO_NOTIFY_MQTT_PASSWORD_WIS2BOX=localbroker-password
      - WIS2BOX_BROKER_HOST=mosquitto
      - WIS2BOX_BROKER_PORT=1883
      - WIS2BOX_BROKER_USERNAME=localbroker-admin
      - WIS2BOX_BROKER_PASSWORD=localbroker-password
      - WIS2BOX_STORAGE_SOURCE=http://minio:9000
      - WIS2BOX_STORAGE_USERNAME=minio-admin
      - WIS2BOX_STORAGE_PASSWORD=minio-password
      - WIS2BOX_BROKER_PUBLIC=mqtt://localbroker-admin:localbroker-password@mosquitto:1883
      - WIS2BOX_DATADIR=/data/wis2box
      - WIS2BOX_LOGGING_LOGLEVEL=INFO
    volumes:
      - ../tests/data:/data/wis2box:rw
    depends_on:
      minio:
        condition: service_healthy
      mosquitto:
        condition: service_started
      wis2box-api:
        condition: service_healthy
    command: ["wis2box", "pubsub" , "subscribe"]