version: '3'

services:
  samba:
    container_name: samba
    image: dperson/samba
    environment:
      TZ: 'Etc/UTC'
    env_file:
      - ../default.env
      - ../../dev.env
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${WIS2BOX_DATADIR}/data/public:/data/public:z
    command: '-s "Mount;/mnt" -s "wis2box Volume;/data/public;yes;no;no;wis2box" -u "wis2box;wis2box" -p'
