version: "3"

services:
  webdav:
    image: bytemark/webdav
    restart: always
    container_name: wis2box-webdav-incoming
    environment:
      AUTH_TYPE: Digest
      USERNAME: ${WEBDAV_USERNAME:-webdav}
      PASSWORD: ${WEBDAV_PWD:-webdav}
    ports:
      - 80:80
    volumes:
      - ${WIS2BOX_HOST_DATADIR}/data/incoming:/var/lib/dav/data/incoming:rw
      - ${WIS2BOX_HOST_DATADIR}/data/public:/var/lib/dav/data/public:rw
