name: build documentation ⚙️

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: setup Python
      with:
        python-version: 3.8
    - name: build docs ⚙️
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get install -y pandoc"
        docs-folder: "docs/"
