name: flake8 ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
