name: test docker deployment ⚙️

on: [ push, pull_request ]

jobs:
  main:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: setup Python
      with:
        python-version: 3.8
    - name: install requirements 📦
      run: |
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: setup wis2box configuration
      run: |
        cp tests/test.env dev.env
        cat dev.env
        python3 wis2box-ctl.py config
    - name: build wis2box images and start containers ⚙️
      run: |
        python3 wis2box-ctl.py build
        python3 wis2box-ctl.py start
        sleep 5
        python3 wis2box-ctl.py status
    - name: test wis2box data ingest/process/publish workflow ⚙️
      run: |
        docker exec `docker ps -q --filter ancestor=wis2box_project_wis2box` sh -c " \
          wis2box environment create \
          && wis2box environment show \
          && wis2box data setup --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed \
          && wis2box data info --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed \
          && wis2box metadata station cache /data/wis2box/metadata/station/station_list.csv \
          && wis2box metadata station publish-collection \
          && wis2box metadata discovery publish /data/wis2box/metadata/discovery/surface-weather-observations.yml \
          && wis2box data ingest --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed -p /data/wis2box/observations \
          && wis2box api add-collection --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed /data/wis2box/metadata/discovery/surface-weather-observations.yml \
          && wis2box api add-collection-items --recursive --path /data/wis2box/data/public"
    - name: restart wis2box API container 🏁
      run: |
        sleep 10
        python3 wis2box-ctl.py status -a
    - name: run integration tests ⚙️
      run: |
        pytest -s tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
    - name: build docs ⚙️
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get install -y pandoc && pip3 install nbsphinx ipython_genutils jinja2==3.0.3"
        docs-folder: "docs/"
