name: test docker deployment ⚙️

on: [ push, pull_request ]

jobs:
  main:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python 3.8
      with:
        python-version: 3.8
    - name: Install requirements 📦
      run: |
        #sudo apt-get update -y && sudo apt-get install -y pandoc
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: wis2box configuration
      run: |
        cp tests/test.env dev.env
        cat dev.env
        python3 wis2box-ctl.py config
    - name: build wis2box ⚙️
      run: |
        python3 wis2box-ctl.py build
        python3 wis2box-ctl.py start
        python3 wis2box-ctl.py status
    - name: generate wis2box collection
      run: |
        docker exec `docker ps -q --filter ancestor=wis2box_project_wis2box` sh -c " \
          wis2box environment create \
          && wis2box environment show \
          && wis2box data setup --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed \
          && wis2box data info --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed \
          && wis2box metadata station cache /data/wis2box/metadata/station/station_list.csv \
          && wis2box metadata station publish-collection \
          && wis2box metadata discovery publish /data/wis2box/metadata/discovery/surface-weather-observations.yml \
          && wis2box data ingest --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed -p /data/wis2box/observations/WIGOS_0-454-2-AWSNAMITAMBO_2021-07-07.csv \
          && wis2box api add-collection --topic-hierarchy data.core.observations-surface-land.mw.FWCL.landFixed /data/wis2box/metadata/discovery/surface-weather-observations.yml \
          && wis2box api add-collection-items --recursive --path /data/wis2box/data/public"
    - name: run wis2box
      run: |
        python3 wis2box-ctl.py restart pygeoapi
        sleep 30
        python3 wis2box-ctl.py status -a
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: run integration tests ⚙️
      run: |
        pytest tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
    - name: build docs ⚙️
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "sudo apt-get install -y pandoc && pip3 install nbsphinx"
        docs-folder: "docs/"
