name: test docker deployment ⚙️

on: [ push, pull_request ]

jobs:
  main:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python 3.8
      with:
        python-version: 3.8
    - name: Install requirements 📦
      run: |
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: wis2node configuration
      run: |
        cp tests/test.env dev.env
        echo dev.env
        python3 wis2node-ctl.py config
    - name: build wis2node ⚙️
      run: |
        python3 wis2node-ctl.py build
        python3 wis2node-ctl.py start
        python3 wis2node-ctl.py status
    - name: generate wis2node collection
      run: |
        docker exec `docker ps -q --filter ancestor=wis2node_project_wis2node` sh -c " \
          wis2node environment create \
          && wis2node environment show \
          && wis2node data setup --topic-hierarchy observations-surface-land.mw.FWCL.landFixed \
          && wis2node data info --topic-hierarchy observations-surface-land.mw.FWCL.landFixed \
          && wis2node metadata station cache /data/wis2node/data/metadata/station/station_list.csv \
          && wis2node metadata station publish-collection \
          && wis2node metadata discovery publish /data/wis2node/data/metadata/discovery/surface-weather-observations.yml \
          && wis2node data ingest -th observations-surface-land.mw.FWCL.landFixed -p /data/wis2node/data/observations/WIGOS_0-454-2-AWSNAMITAMBO_20210707.csv \
          && wis2node api add-collection /data/wis2node/data/metadata/discovery/surface-weather-observations.yml --topic-hierarchy observations-surface-land.mw.FWCL.landFixed \
          && wis2node api add-collection-items -r -p /data/wis2node/data/public"
    - name: run wis2node
      run: |
        python3 wis2node-ctl.py restart pygeoapi
        sleep 30
        python3 wis2node-ctl.py status -a
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: run integration tests ⚙️
      run: |
        pytest tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
