name: test docker deployment ⚙️

on: [ push, pull_request ]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        ingest: [cli, event]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: setup Python
      with:
        python-version: 3.8
    - name: install requirements 📦
      run: |
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: software running on 📦
      run: |
        docker version
        docker compose version
        python3 -V
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: setup wis2box configuration
      run: |
        cp tests/test.env dev.env
        cat dev.env
        python3 wis2box-ctl.py config
    - name: build wis2box
      run: |
        python3 wis2box-ctl.py build
        python3 wis2box-ctl.py update
    - name: start containers ⚙️
      run: |
        python3 wis2box-ctl.py start
        python3 wis2box-ctl.py status -a
    - name: Setup wis2box collections ⚙️
      run: |
        docker exec wis2box sh -c " \
          wis2box environment create \
          && wis2box environment show \
          && wis2box data setup -th data.core.observations-surface-land.mw.FWCL.landFixed \
          && wis2box data info -th data.core.observations-surface-land.mw.FWCL.landFixed \
          && wis2box metadata discovery publish /data/wis2box/metadata/discovery/surface-weather-observations.yml \
          && wis2box metadata station cache /data/wis2box/metadata/station/station_list.csv \
          && wis2box metadata station publish-collection \
          && wis2box api add-collection -th data.core.observations-surface-land.mw.FWCL.landFixed /data/wis2box/metadata/discovery/surface-weather-observations.yml"
    - name: Ingest & publish data from CLI
      if: ${{ matrix.ingest == 'cli' }}
      run: |
        docker exec wis2box sh -c " \
          wis2box data ingest -th data.core.observations-surface-land.mw.FWCL.landFixed -p /data/wis2box/observations"
    - name: Ingest & publish data with event workflow
      if: ${{ matrix.ingest == 'event' }}
      run: |
        python3 tests/copy_to_incoming.py tests/data/observations/* wis2box-incoming/data/core/observations-surface-land/mw/FWCL/landFixed
    - name: run integration tests ⚙️
      run: |
        sleep 25
        pytest -s tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
    - name: build docs ⚙️
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get install -y pandoc && pip3 install nbsphinx ipython_genutils jinja2==3.0.3"
        docs-folder: "docs/"
