name: test docker deployment ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: setup Python
      with:
        python-version: 3.8
    - name: install requirements 📦
      run: |
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: software running on 📦
      run: |
        docker version
        docker compose version
        python3 -V
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: setup wis2box configuration
      run: |
        cp tests/test.env dev.env
        cat dev.env
        python3 wis2box-ctl.py config
    - name: build wis2box
      run: |
        python3 wis2box-ctl.py build
        python3 wis2box-ctl.py update
    - name: start containers ⚙️
      run: |
        python3 wis2box-ctl.py start
        python3 wis2box-ctl.py status -a
        docker logs wis2box
    - name: setup wis2box ⚙️
      run: |
        docker exec wis2box sh -c " \
          wis2box environment create \
          && wis2box environment show \
          && wis2box api setup"
    - name: add Malawi data 🇲🇼
      run: |
        docker exec wis2box sh -c ' \
          export TOPIC_HIERARCHY=data.core.observations-surface-land.mw.FWCL.landFixed \
          && export DISCOERY_METADATA=/data/wis2box/metadata/discovery/mw-surface-weather-observations.yml \
          && wis2box metadata discovery publish $DISCOERY_METADATA \
          && wis2box api add-collection -th $TOPIC_HIERARCHY $DISCOERY_METADATA \
          && wis2box data ingest -th $TOPIC_HIERARCHY -p /data/wis2box/observations/malawi \
          && wis2box metadata station sync /data/wis2box/metadata/station/station_list.csv'
    - name: add Italy data 🇮🇹
      run: |
        docker exec wis2box sh -c ' \
          export TOPIC_HIERARCHY=data.core.observations-surface-land.it.FWCL.landFixed \
          && export DISCOERY_METADATA=/data/wis2box/metadata/discovery/it-surface-weather-observations.yml \
          && wis2box metadata discovery publish $DISCOERY_METADATA \
          && wis2box api add-collection -th $TOPIC_HIERARCHY $DISCOERY_METADATA \
          && wis2box data ingest -th $TOPIC_HIERARCHY -p /data/wis2box/observations/italy'
    - name: add Algeria data 🇩🇿
      run: |
        docker exec wis2box sh -c ' \
          export TOPIC_HIERARCHY=data.core.observations-surface-land.dz.FWCL.landFixed \
          && export DISCOERY_METADATA=/data/wis2box/metadata/discovery/dz-surface-weather-observations.yml \
          && wis2box data info -th $TOPIC_HIERARCHY \
          && wis2box metadata discovery publish $DISCOERY_METADATA \
          && wis2box api add-collection -th $TOPIC_HIERARCHY $DISCOERY_METADATA \
          && wis2box data ingest -th $TOPIC_HIERARCHY -p /data/wis2box/observations/algeria'
    - name: run integration tests ⚙️
      run: |
        sleep 10
        pytest -s tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
    - name: build docs ⚙️
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get install -y pandoc && pip3 install nbsphinx ipython_genutils jinja2==3.0.3"
        docs-folder: "docs/"
    - name: Failed tests
      if: ${{ failure() }}
      run: |
        docker-compose --file docker/docker-compose.yml --file docker/docker-compose.override.yml --file docker/docker-compose.monitoring.yml --env-file dev.env --project-name wis2box_project ps
        docker-compose --file docker/docker-compose.yml --file docker/docker-compose.override.yml --file docker/docker-compose.monitoring.yml --env-file dev.env --project-name wis2box_project logs
