name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      FOO: bar

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: setup test data ⚙️ PostgreSQL/PostGIS 📦
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
      run: |
        echo "Setting up test data"
        cd tests
        python3 load_obs_data.py data/observations/
        docker compose up -d
    - name: build Wis2node ⚙️
      run: |
        make build
        make up  
    - name: generate wis2node collection
      run: |
        docker exec -d `docker ps -q --filter ancestor=wis2node_wis2node` sh -c "\
          wis2node metadata station generate-collection \
          && wis2node metadata discovery publish \
            /app/tests/data/metadata/discovery/surface-weather-observations.yml \
          && wis2node data observations process \
            --discovery-metadata /app/tests/data/metadata/discovery/surface-weather-observations.yml \
            --station-metadata /app/tests/data/metadata/station/0-454-2-AWSNAMITAMBO.json \
            --mappings /app/tests/data/config/malawi_synop_bufr.json \
            --geojson_mappings /app/tests/data/config/malawi_synop_json.geojson \
            /app/tests/data/observations/Namitambo_SYNOP.csv \
          && exit 0"
    - name: run wis2node
      run: |
        sleep 10
        make up
        docker ps -a
        docker exec -d `docker ps -q --filter ancestor=wis2node_pygeoapi` sh -c "\
          cat/tmp/pygeoapi.log \
          && exit 0"
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: run integration tests ⚙️
      run: |
        pytest tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
