name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      FOO: bar

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        python3 setup.py install
    - name: setup test data ⚙️ PostgreSQL/PostGIS 📦
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
      run: |
        echo "Setting up test data"
        cd tests
        python3 load_obs_data.py data/observations/
        docker run -it --rm -d --name db $(docker build -t db -q .) \
          -p 5432:5432 \
          -e POSTGRES_USER -e POSTGRES_PASSWORD -e POSTGRES_DB 
    - name: run Wis2node
      run: |
        make up
        docker ps
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: run integration tests ⚙️
      run: |
        pytest tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
