name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    env:
      FOO: bar

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=100
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
        sudo swapon -a
    - name: setup test data ⚙️ PostgreSQL/PostGIS 📦
      env:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
      run: |
        echo "Setting up test data"
        cd tests
        python3 load_obs_data.py data/observations/
        docker compose up -d
    - name: build Wis2node ⚙️
      run: |
        make build
        make up
    - name: verify wis2node is running
      run: |
        docker ps
    - name: generate wis2node collection
      run: |
        docker exec -i wis2node sh -c "\
          wis2node metadata station generate-collection"
    - name: publish wis2node discovery metadata
      run: |
        docker exec -i wis2node sh -c "\
          wis2node metadata discovery publish \
            /app/tests/data/metadata/discovery/surface-weather-observations.yml"
    - name: publish wis2node observations
      run: |
        docker exec -i wis2node sh -c "\
          wis2node data observations process \
            --discovery-metadata /app/tests/data/metadata/discovery/surface-weather-observations.yml \
            --station-metadata /app/tests/data/metadata/station/0-454-2-AWSNAMITAMBO.json \
            --mappings /app/tests/data/config/malawi_synop_bufr.json \
            --geojson_mappings /app/tests/data/config/malawi_synop_json.geojson \
            /app/tests/data/observations/Namitambo_SYNOP.csv"
    - name: run wis2node
      run: |
        make up
        docker ps
    - name: run unit tests ⚙️
      run: |
        pytest tests/unit
    - name: run integration tests ⚙️
      run: |
        pytest tests/integration
    - name: run flake8 ⚙️
      run: |
        find . -type f -name "*.py" | xargs flake8
