name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build wis2box-management
        run: |
          docker build -t wis2box-management:test wis2box-management
      - name: Run Trivy vulnerability scanner on wis2box-management
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'wis2box-management:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'